### ISSUE TITLE
Using turbo-telegram for getting update by webhook

### ISSUE THREAD

**Issue by srazi** [luastoned/turbo-telegram#1]
I'm trying to use turbo-telegram using `webhook` on my VPS.

Because of this I have to setup ssl key/cert and pass them to `turbo`. I successfully setup key/cert and `turbo` accept ssl requests. I mean for example with `helloworld.lua` example `https://example.com/hello` correctly prints `Hello World!`. (I also tested letsencrypt )

This is how I setup my application:

``` lua
TURBO_SSL = true
local telegram = require("turbo-telegram/telegram")
local turbo = require("turbo")
local bot_token = "xxxx:xxxxxxxxxxxx"

telegram.setBotToken(bot_token)

local BotHandler= class("BotHandler", turbo.web.RequestHandler)

function BotHandler:get(arg1, arg2)
    if arg1 == "hello" then
        self:write("Hello World!")
    else
        self:write("arg1: "..arg1.." - arg2: "..(arg2 or "NO_ARG2"))
    end
end

local SSL_CERT_FILE_PATH = "/path/to/cert.pem"
local SSL_KEY_FILE_PATH = "/path/to/privkey.pem"

turbo.web.Application({
        {"/([a-zA-Z0-9]+)/(.*)", BotHandler}
    }
):listen(443, turbo.socket.INADDR_ANY, {
        ssl_options = {
            key_file = SSL_KEY_FILE_PATH,
            cert_file = SSL_CERT_FILE_PATH
        }
    }
)

turbo.ioloop.instance():start()
```

but after I set `https://example.com` as webhook (directly not by turbo-telegram) it repeatedly prints the following error:

``` lua
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
[E 2016/04/28 21:06:35] [ioloop.lua] Error in IOLoop handler.
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
/usr/local/share/lua/5.1/turbo/crypto_linux.lua:290: Could not do SSL handshake.
SSL error. error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/turbo/crypto_linux.lua:290: in function 'ssl_do_handshake'
        /usr/local/share/lua/5.1/turbo/iostream.lua:1197: in function '_do_ssl_handshake'
        /usr/local/share/lua/5.1/turbo/iostream.lua:1213: in function '_handle_read'
        /usr/local/share/lua/5.1/turbo/iostream.lua:484: in function </usr/local/share/lua/5.1/turbo/iostream.lua:475>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/turbo/ioloop.lua:541: in function '_run_handler'
        /usr/local/share/lua/5.1/turbo/ioloop.lua:453: in function '_event_poll'
        /usr/local/share/lua/5.1/turbo/ioloop.lua:442: in function 'start'
        test.lua:28: in main chunk
        [C]: at 0x00404d60
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
```

What's going wrong? Why telegram cant `handshake` to webhook URL?
`unknown ca` ? I uploded cert file when setting `webhook`.

**Comment by luastoned** [comment]
Hey, I thought this issue is/was related to https://github.com/kernelsauce/turbo/issues/239 but that got locked so I will investigate what's going on.

I myself use nginx as the frontend/reverse proxy (thus nginx handles SSL) so that might be a temporary solution.

**Comment by srazi** [comment]
Oh sorry if I didn't update my issue. Indeed it was a strange behavior of Telegram servers when setting webhook, I was using  a free `tk` domain name for my server and first time telegram set the webhook but next time it didn't set webhook after some trial-n-error I found that it seems Telegram server cant resolve my domain name to server IP because of this I create cert/key for server IP instead of its domain name and it worked :D 

I will close this issue.

Thanks for your time. :)
